language:
 - "node_js"
node_js:
 - "0.11"
 - "0.10"

before_install:
 - "sudo apt-add-repository -y ppa:jon-severinsson/ffmpeg"
 - "sudo apt-get update"
 - "sudo apt-get install ffmpeg"

install:
 - "npm install"
 - "npm install forever --global"
 - "npm install jasmine-node --global"

before_script:
 - "forever start server.js"

after_script:
 - "npm stop"
